"""add organization type

Revision ID: 0240b4696b7c
Revises: c1bbaef6ea44
Create Date: 2026-08-05 03:45:44.826982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0240b4696b7c'
down_revision: Union[str, Sequence[str], None] = 'c1bbaef6ea44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('organization_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'organization_type')
    # ### end Alembic commands ###
