"""enhance wards structure

Revision ID: 0d4579d4f887
Revises: 41887f7c4c90
Create Date: 2026-08-06 09:17:38.039221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4579d4f887'
down_revision: Union[str, Sequence[str], None] = '41887f7c4c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wards', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('wards', sa.Column('code', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'wards', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wards', type_='foreignkey')
    op.drop_column('wards', 'code')
    op.drop_column('wards', 'department_id')
    # ### end Alembic commands ###
