"""create vital signs table

Revision ID: 167524cf4296
Revises: 6bd51fb2429b
Create Date: 2026-08-05 07:31:55.306661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167524cf4296'
down_revision: Union[str, Sequence[str], None] = '6bd51fb2429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vital_signs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pulse_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('respiratory_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('systolic_pressure', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diastolic_pressure', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vital_signs')
    # ### end Alembic commands ###
