"""add recorder to vital signs

Revision ID: 41887f7c4c90
Revises: 97db4e8f7fcf
Create Date: 2026-08-06 09:12:49.655704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41887f7c4c90'
down_revision: Union[str, Sequence[str], None] = '97db4e8f7fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('recorded_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'vital_signs', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vital_signs', type_='foreignkey')
    op.drop_column('vital_signs', 'recorded_by')
    # ### end Alembic commands ###
