"""add bed code

Revision ID: 53956b6f1dfa
Revises: 0d4579d4f887
Create Date: 2026-08-06 09:21:19.513231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53956b6f1dfa'
down_revision: Union[str, Sequence[str], None] = '0d4579d4f887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beds', sa.Column('bed_code', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'beds', ['bed_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beds', type_='unique')
    op.drop_column('beds', 'bed_code')
    # ### end Alembic commands ###
