"""add appointment and department to encounters

Revision ID: 5f09d38fd5e4
Revises: ddd014aefd2e
Create Date: 2026-08-06 09:05:32.157192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f09d38fd5e4'
down_revision: Union[str, Sequence[str], None] = 'ddd014aefd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('appointment_id', sa.UUID(), nullable=True))
    op.add_column('encounters', sa.Column('department_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'encounters', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'encounters', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_column('encounters', 'department_id')
    op.drop_column('encounters', 'appointment_id')
    # ### end Alembic commands ###
