"""make nursing note admission optional

Revision ID: 97db4e8f7fcf
Revises: 5f09d38fd5e4
Create Date: 2026-08-06 09:09:04.440826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97db4e8f7fcf'
down_revision: Union[str, Sequence[str], None] = '5f09d38fd5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nursing_notes', 'admission_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('nursing_notes', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nursing_notes', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('nursing_notes', 'admission_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
