"""enhance discharge workflow

Revision ID: a525f98978e5
Revises: b1bcac2fa144
Create Date: 2026-08-06 09:35:57.943737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a525f98978e5'
down_revision: Union[str, Sequence[str], None] = 'b1bcac2fa144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discharges', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('discharges', sa.Column('disposition', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discharges', 'disposition')
    op.drop_column('discharges', 'status')
    # ### end Alembic commands ###
