"""add encounter recorded by

Revision ID: b2a9fe56060f
Revises: 167524cf4296
Create Date: 2026-08-05 07:39:46.873021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a9fe56060f'
down_revision: Union[str, Sequence[str], None] = '167524cf4296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('recorded_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'encounters', 'users', ['recorded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_column('encounters', 'recorded_by')
    # ### end Alembic commands ###
