"""enhance procedures for surgical workflow

Revision ID: ba4a37c35fb1
Revises: f9c627f8554a
Create Date: 2026-08-06 09:56:56.809808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4a37c35fb1'
down_revision: Union[str, Sequence[str], None] = 'f9c627f8554a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('procedure_category', sa.String(length=100), nullable=False))
    op.add_column('procedures', sa.Column('requires_theatre', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedures', 'requires_theatre')
    op.drop_column('procedures', 'procedure_category')
    # ### end Alembic commands ###
