"""add recorded timestamp to clinical notes

Revision ID: ba5a0e319570
Revises: a525f98978e5
Create Date: 2026-08-06 09:42:40.109678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5a0e319570'
down_revision: Union[str, Sequence[str], None] = 'a525f98978e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_notes', 'recorded_at')
    # ### end Alembic commands ###
