"""add ward to admissions

Revision ID: bef6f041de3d
Revises: 53956b6f1dfa
Create Date: 2026-08-06 09:25:05.807222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef6f041de3d'
down_revision: Union[str, Sequence[str], None] = '53956b6f1dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('ward_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'admissions', 'wards', ['ward_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_column('admissions', 'ward_id')
    # ### end Alembic commands ###
