"""rename user hospital_id to organization_id

Revision ID: c1bbaef6ea44
Revises: 8719b000baa5
Create Date: 2026-08-04 21:06:10.619468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bbaef6ea44'
down_revision: Union[str, Sequence[str], None] = '8719b000baa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('users_hospital_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'hospital_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hospital_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_hospital_id_fkey'), 'users', 'organizations', ['hospital_id'], ['id'])
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
