"""create insurance settlements table

Revision ID: c59ff93b658c
Revises: 7aa59fda6565
Create Date: 2026-08-05 11:35:31.828427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59ff93b658c'
down_revision: Union[str, Sequence[str], None] = '7aa59fda6565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('insurance_claim_id', sa.UUID(), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['insurance_claim_id'], ['insurance_claims.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_settlements')
    # ### end Alembic commands ###
